import { Knex } from 'knex'
import type { StorageKnex } from '../StorageKnex'
import { TrxToken } from '../../sdk/WalletStorage.interfaces'
import { WalletError } from '../../sdk/WalletError'
import type { ProvenTxReqStatus } from '../../sdk/types'
import { TableTransaction } from '../schema/tables/TableTransaction'
import { TableOutput } from '../schema/tables/TableOutput'

const provenTxReqStatusesSafeForInputRestore: ProvenTxReqStatus[] = ['invalid', 'doubleSpend']

/**
 * Looks for unpropagated state:
 *
 * 1. set transactions to 'failed' if not already failed and provenTxReq with matching txid has status of 'invalid'.
 * 2. sets outputs to spendable true, spentBy undefined if spentBy is a terminal failed transaction.
 * 3. sets outputs generated by terminal failed transactions to spendable false, spentBy undefined.
 * 4. sets transactions to 'completed' if provenTx with matching txid exists and current provenTxId is null.
 *
 * @param storage
 * @param args
 * @returns
 */
export async function reviewStatus(
  storage: StorageKnex,
  args: { agedLimit: Date; trx?: TrxToken }
): Promise<{ log: string }> {
  const r: { log: string } = { log: '' }

  const runReviewStatusQuery = async (pq: ReviewStatusQuery): Promise<void> => {
    try {
      pq.sql = pq.q.toString()
      const count = await pq.q
      if (count > 0) {
        r.log += `${count} ${pq.log}\n`
      }
    } catch (error_: unknown) {
      // eslint-disable-next-line @typescript-eslint/no-unused-vars
      const e = WalletError.fromUnknown(error_)
      throw error_
    }
  }

  const k = storage.toDb(args.trx)

  const qs: ReviewStatusQuery[] = []

  qs.push(
    {
      log: "transactions updated to status of 'failed' where provenTxReq with matching txid is 'invalid'",
      /*
          UPDATE transactions SET status = 'failed'
          WHERE exists(select 1 from proven_tx_reqs as r where transactions.txid = r.txid and r.status = 'invalid')
          */
      q: k<TableTransaction>('transactions')
        .update({ status: 'failed' })
        .whereNot({ status: 'failed' })
        .whereExists(function () {
          this.select(k.raw(1))
            .from('proven_tx_reqs as r')
            .whereRaw("transactions.txid = r.txid and r.status = 'invalid'")
        })
    },
    {
      log: 'outputs updated to spendable where spentBy is a failed transaction with no blocking ProvenTxReq',
      /*
          UPDATE outputs SET spentBy = null, spendable = 1
          where exists(select 1 from transactions as t where outputs.spentBy = t.transactionId and t.status = 'failed')
          and not exists(select 1 from proven_tx_reqs as r where r.txid = t.txid and r.status not in ('invalid', 'doubleSpend'))
          */
      q: k<TableOutput>('outputs')
        .update({ spentBy: null as unknown as undefined, spendable: true })
        .whereExists(function () {
          this.select(k.raw(1))
            .from('transactions as t')
            .whereRaw("outputs.spentBy = t.transactionId and t.status = 'failed'")
            .whereNotExists(function () {
              // A failed transaction can still be reconciled from active or valid reqs.
              // Only terminal failure reqs are safe for input restoration.
              this.select(k.raw(1))
                .from('proven_tx_reqs as r')
                .whereRaw('r.txid = t.txid')
                .whereNotIn('r.status', provenTxReqStatusesSafeForInputRestore)
            })
            .whereNotExists(function () {
              // Outputs generated by a failed transaction are not valid inputs to restore.
              this.select(k.raw(1))
                .from('transactions as source')
                .whereRaw("outputs.transactionId = source.transactionId and source.status = 'failed'")
            })
        })
    },
    {
      log: 'outputs updated to not spendable where generated by a failed transaction with no blocking ProvenTxReq',
      /*
          UPDATE outputs SET spentBy = null, spendable = 0
          where exists(select 1 from transactions as t where outputs.transactionId = t.transactionId and t.status = 'failed')
          and not exists(select 1 from proven_tx_reqs as r where r.txid = t.txid and r.status not in ('invalid', 'doubleSpend'))
          */
      q: k<TableOutput>('outputs')
        .update({ spentBy: null as unknown as undefined, spendable: false })
        .where(function () {
          this.where({ spendable: true }).orWhereNotNull('spentBy')
        })
        .whereExists(function () {
          this.select(k.raw(1))
            .from('transactions as t')
            .whereRaw("outputs.transactionId = t.transactionId and t.status = 'failed'")
            .whereNotExists(function () {
              // A failed transaction can still be reconciled from active or valid reqs.
              // Only terminal failure reqs are safe for output neutralization.
              this.select(k.raw(1))
                .from('proven_tx_reqs as r')
                .whereRaw('r.txid = t.txid')
                .whereNotIn('r.status', provenTxReqStatusesSafeForInputRestore)
            })
        })
    },
    {
      log: "transactions updated with provenTxId and status of 'completed' where provenTx with matching txid exists",
      /*
          UPDATE transactions SET status = 'completed', provenTxId = p.provenTxId
          FROM proven_txs p
          WHERE transactions.txid = p.txid AND transactions.provenTxId IS NULL
          */
      q: k<TableTransaction>('transactions')
        .update({
          status: 'completed',
          provenTxId: k.raw('(SELECT provenTxId FROM proven_txs AS p WHERE transactions.txid = p.txid)')
        })
        .whereNull('provenTxId')
        .whereExists(function () {
          this.select(k.raw(1)).from('proven_txs as p').whereRaw('transactions.txid = p.txid')
        })
    }
  )

  for (const q of qs) await runReviewStatusQuery(q)

  return r
}

interface ReviewStatusQuery {
  q: Knex.QueryBuilder<any, number>
  sql?: string
  log: string
}
