import { PrivateKey, ProtoWallet } from '@bsv/sdk'
import {
  buildPairingUri,
  parsePairingUri,
  verifyPairingSignature
} from '../src/shared/pairingUri.js'
import { bytesToBase64url } from '../src/shared/encoding.js'
import { PROTOCOL_ID } from '../src/types.js'

// A valid compressed secp256k1 public key (deterministic for tests)
const BACKEND_KEY = PrivateKey.fromRandom().toPublicKey().toString()

const VALID_BUILD_PARAMS = {
  sessionId: 'session-abc-123',
  backendIdentityKey: BACKEND_KEY,
  protocolID: JSON.stringify(PROTOCOL_ID),
  origin: 'https://app.example.com'
}

describe('buildPairingUri / parsePairingUri roundtrip', () => {
  it('builds a bsv-browser:// URI and parses it back to the original params', () => {
    const uri = buildPairingUri(VALID_BUILD_PARAMS)
    expect(uri).toMatch(/^bsv-browser:\/\//)

    const result = parsePairingUri(uri)
    expect(result.error).toBeNull()
    expect(result.params).not.toBeNull()

    const p = result.params!
    expect(p.topic).toBe('session-abc-123')
    expect(p.backendIdentityKey).toBe(BACKEND_KEY)
    expect(p.origin).toBe('https://app.example.com')
    expect(JSON.parse(p.protocolID)).toEqual(PROTOCOL_ID)
  })

  it('accepts a custom schema when passed in acceptedSchemas', () => {
    const uri = buildPairingUri({ ...VALID_BUILD_PARAMS, schema: 'my-app' })
    expect(parsePairingUri(uri, new Set(['my-app:'])).error).toBeNull()
    // rejected without the custom schema
    expect(parsePairingUri(uri).error).toBeTruthy()
  })

  it('relay URL is not embedded in the URI', () => {
    const uri = buildPairingUri(VALID_BUILD_PARAMS)
    expect(uri).not.toContain('relay=')
  })

  it('old QR codes with a relay param are accepted (relay is silently ignored)', () => {
    // Backward compat: QR codes generated by older versions included relay=…
    // The new parser must not reject them — it simply ignores the extra field.
    const base = buildPairingUri(VALID_BUILD_PARAMS)
    const uri = base + '&relay=wss%3A%2F%2Fold.example.com'
    const result = parsePairingUri(uri)
    expect(result.error).toBeNull()
    expect(result.params).not.toBeNull()
    // relay must not leak into params
    expect((result.params as unknown as Record<string, string>)['relay']).toBeUndefined()
  })

  it('expiry is in the future for a freshly built URI', () => {
    const uri = buildPairingUri(VALID_BUILD_PARAMS)
    const result = parsePairingUri(uri)
    expect(result.error).toBeNull()
    expect(Number(result.params!.expiry)).toBeGreaterThan(Date.now() / 1000)
  })

  it('respects custom pairingTtlMs', () => {
    const tenMinutes = 10 * 60 * 1000
    const uri = buildPairingUri({ ...VALID_BUILD_PARAMS, pairingTtlMs: tenMinutes })
    const result = parsePairingUri(uri)
    expect(result.error).toBeNull()
    // expiry should be roughly 10 min from now (allow ±5 s for test execution)
    const expiryMs = Number(result.params!.expiry) * 1000
    expect(expiryMs).toBeGreaterThan(Date.now() + tenMinutes - 5_000)
    expect(expiryMs).toBeLessThan(Date.now() + tenMinutes + 5_000)
  })

  it('sig field roundtrips through buildPairingUri / parsePairingUri', () => {
    const uri = buildPairingUri({ ...VALID_BUILD_PARAMS, sig: 'dGVzdA' })
    const result = parsePairingUri(uri)
    expect(result.error).toBeNull()
    expect(result.params!.sig).toBe('dGVzdA')
  })

  it('sig is absent when not passed to buildPairingUri', () => {
    const uri = buildPairingUri(VALID_BUILD_PARAMS)
    const result = parsePairingUri(uri)
    expect(result.params!.sig).toBeUndefined()
  })
})

describe('parsePairingUri validation', () => {
  it('rejects an unrecognised URI scheme', () => {
    const result = parsePairingUri('https://example.com/pair?foo=bar')
    expect(result.error).toBeTruthy()
    expect(result.params).toBeNull()
  })

  it('rejects a URI with missing required fields', () => {
    // Missing backendIdentityKey
    const uri = 'bsv-browser://pair?topic=abc&origin=https://app.example.com'
    const result = parsePairingUri(uri)
    expect(result.error).toBeTruthy()
  })

  it('rejects an expired QR code', () => {
    const p = new URLSearchParams({
      topic: 'x',
      backendIdentityKey: BACKEND_KEY,
      protocolID: JSON.stringify(PROTOCOL_ID),
      origin: 'https://app.example.com',
      expiry: String(Math.floor(Date.now() / 1000) - 60) // 60 s in the past
    })
    const result = parsePairingUri(`bsv-browser://pair?${p}`)
    expect(result.error).toMatch(/expired/i)
  })

  it('rejects a malformed backendIdentityKey', () => {
    const p = new URLSearchParams({
      topic: 'x',
      backendIdentityKey: 'not-a-pubkey',
      protocolID: JSON.stringify(PROTOCOL_ID),
      origin: 'https://app.example.com',
      expiry: String(Math.floor(Date.now() / 1000) + 120)
    })
    const result = parsePairingUri(`bsv-browser://pair?${p}`)
    expect(result.error).toMatch(/public key/i)
  })

  it('rejects an origin that is not http:// or https://', () => {
    const p = new URLSearchParams({
      topic: 'x',
      backendIdentityKey: BACKEND_KEY,
      protocolID: JSON.stringify(PROTOCOL_ID),
      origin: 'ftp://app.example.com',
      expiry: String(Math.floor(Date.now() / 1000) + 120)
    })
    const result = parsePairingUri(`bsv-browser://pair?${p}`)
    expect(result.error).toMatch(/origin/i)
  })
})

// ── Signature tests ───────────────────────────────────────────────────────────

describe('verifyPairingSignature', () => {
  let backendKey: PrivateKey
  let backendKeyHex: string
  let wallet: ProtoWallet

  beforeEach(() => {
    backendKey = PrivateKey.fromRandom()
    backendKeyHex = backendKey.toPublicKey().toString()
    wallet = new ProtoWallet(backendKey)
  })

  async function makeSignedParams(
    overrides?: Partial<{
      topic: string
      backendIdentityKey: string
      origin: string
      expiry: string
    }>
  ) {
    const topic = overrides?.topic ?? 'test-session-id'
    const bik = overrides?.backendIdentityKey ?? backendKeyHex
    const origin = overrides?.origin ?? 'https://app.example.com'
    const expiry = overrides?.expiry ?? String(Math.floor(Date.now() / 1000) + 120)

    const data = Array.from(new TextEncoder().encode(`${topic}|${bik}|${origin}|${expiry}`))
    const { signature } = await wallet.createSignature({
      data,
      protocolID: [0, 'qr pairing'],
      keyID: topic,
      counterparty: 'anyone'
    })
    const sig = bytesToBase64url(signature as number[])

    return {
      topic,
      backendIdentityKey: bik,
      protocolID: JSON.stringify(PROTOCOL_ID),
      origin,
      expiry,
      sig
    }
  }

  it('returns true for a valid signature', async () => {
    expect(await verifyPairingSignature(await makeSignedParams())).toBe(true)
  })

  it('returns false when backendIdentityKey is tampered', async () => {
    const params = await makeSignedParams()
    const otherKey = PrivateKey.fromRandom().toPublicKey().toString()
    expect(await verifyPairingSignature({ ...params, backendIdentityKey: otherKey })).toBe(false)
  })

  it('returns false when origin is tampered', async () => {
    const params = await makeSignedParams()
    expect(await verifyPairingSignature({ ...params, origin: 'https://evil.example.com' })).toBe(
      false
    )
  })

  it('returns false when expiry is tampered', async () => {
    const params = await makeSignedParams()
    expect(
      await verifyPairingSignature({ ...params, expiry: String(Number(params.expiry) + 9999) })
    ).toBe(false)
  })

  it('returns true (no-op) when sig is absent', async () => {
    const { sig: _sig, ...unsigned } = await makeSignedParams()
    expect(await verifyPairingSignature(unsigned)).toBe(true)
  })

  it('returns false for a corrupted sig string', async () => {
    const params = await makeSignedParams()
    expect(await verifyPairingSignature({ ...params, sig: 'AAAAAAAAAA' })).toBe(false)
  })

  it('buildPairingUri + parsePairingUri roundtrips the sig and verifies', async () => {
    const params = await makeSignedParams()
    const uri = buildPairingUri({
      sessionId: params.topic,
      backendIdentityKey: params.backendIdentityKey,
      protocolID: params.protocolID,
      origin: params.origin,
      expiry: Number(params.expiry),
      sig: params.sig
    })
    const result = parsePairingUri(uri)
    expect(result.error).toBeNull()
    expect(result.params!.sig).toBe(params.sig)
    expect(await verifyPairingSignature(result.params!)).toBe(true)
  })
})

// ── Performance tests ─────────────────────────────────────────────────────────

describe('QR signature performance', () => {
  const ITERATIONS = 20

  it(`createSignature: avg < 500 ms over ${ITERATIONS} iterations`, async () => {
    const key = PrivateKey.fromRandom()
    const wallet = new ProtoWallet(key)
    const bik = key.toPublicKey().toString()
    const topic = 'perf-session'
    const origin = 'https://app.example.com'

    const durations: number[] = []
    for (let i = 0; i < ITERATIONS; i++) {
      const expiry = Math.floor((Date.now() + 120_000) / 1000)
      const data = Array.from(new TextEncoder().encode(`${topic}|${bik}|${origin}|${expiry}`))
      const t0 = performance.now()
      await wallet.createSignature({
        data,
        protocolID: [0, 'qr pairing'],
        keyID: topic,
        counterparty: 'anyone'
      })
      durations.push(performance.now() - t0)
    }

    const avg = durations.reduce((a, b) => a + b, 0) / durations.length
    console.log(
      `createSignature avg=${avg.toFixed(2)}ms  min=${Math.min(...durations).toFixed(2)}ms  max=${Math.max(...durations).toFixed(2)}ms`
    )
    expect(avg).toBeLessThan(500)
  }, 30_000)

  it(`verifyPairingSignature: avg < 500 ms over ${ITERATIONS} iterations`, async () => {
    const key = PrivateKey.fromRandom()
    const wallet = new ProtoWallet(key)
    const bik = key.toPublicKey().toString()
    const topic = 'perf-session'
    const origin = 'https://app.example.com'
    const expiry = Math.floor((Date.now() + 120_000) / 1000)

    const data = Array.from(new TextEncoder().encode(`${topic}|${bik}|${origin}|${expiry}`))
    const { signature } = await wallet.createSignature({
      data,
      protocolID: [0, 'qr pairing'],
      keyID: topic,
      counterparty: 'anyone'
    })
    const sig = bytesToBase64url(signature as number[])
    const uri = buildPairingUri({
      sessionId: topic,
      backendIdentityKey: bik,
      protocolID: JSON.stringify(PROTOCOL_ID),
      origin,
      expiry,
      sig
    })
    const { params } = parsePairingUri(uri)

    const durations: number[] = []
    for (let i = 0; i < ITERATIONS; i++) {
      const t0 = performance.now()
      await verifyPairingSignature(params!)
      durations.push(performance.now() - t0)
    }

    const avg = durations.reduce((a, b) => a + b, 0) / durations.length
    console.log(
      `verifyPairingSignature avg=${avg.toFixed(2)}ms  min=${Math.min(...durations).toFixed(2)}ms  max=${Math.max(...durations).toFixed(2)}ms`
    )
    expect(avg).toBeLessThan(500)
  }, 30_000)
})
